version: '3'

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile  # <-- Dockerfile faylini ko'rsatish
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Core:/app
    ports:
      - 8000:8000
